language: java
script:
  - mvn clean install site
notifications:
  recipients:
    email:
      - kontakt@florian-thiery.de
  on_success: always # default: change
  on_failure: always # default: always
